# Generated by Django 6.0.5 on 2026-06-11 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0006_book_min_plan_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_commission_percent', models.DecimalField(decimal_places=2, default=15, help_text='Asilimia ya mfumo (admin) kutoka kwa mauzo ya moja kwa moja ya vitabu (mtumiaji ananunua kitabu maisha yote)', max_digits=5)),
                ('subscription_commission_percent', models.DecimalField(decimal_places=2, default=30, help_text='Asilimia ya mfumo (admin) kutoka kwa mapato yote ya usajili wa kila mwezi, kabla ya kugawanywa kwa waandishi kulingana na usomaji', max_digits=5)),
            ],
            options={
                'verbose_name': 'Mipangilio ya Mapato',
                'verbose_name_plural': 'Mipangilio ya Mapato',
            },
        ),
        migrations.CreateModel(
            name='AuthorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('purchase', 'Mauzo ya Moja kwa Moja'), ('subscription', 'Mgao wa Usajili')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reads', models.PositiveIntegerField(blank=True, help_text='Idadi ya wasomaji wenye usajili waliosoma kitabu hiki mwezi huu', null=True)),
                ('share_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='books.book')),
            ],
            options={
                'verbose_name': 'Mapato ya Mwandishi',
                'verbose_name_plural': 'Mapato ya Waandishi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRevenuePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distributed', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kasha la Mapato ya Usajili',
                'verbose_name_plural': 'Makasha ya Mapato ya Usajili',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ReadingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_events', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tukio la Usomaji',
                'verbose_name_plural': 'Matukio ya Usomaji',
                'unique_together': {('user', 'book', 'year', 'month')},
            },
        ),
    ]
