# Generated by Django 6.0.5 on 2026-06-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rating'),
        ('users', '0002_moderation_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, related_name='followers', to='books.category', verbose_name='Makundi Anayopenda Msomaji'),
        ),
    ]
