# Generated by Django 6.0.5 on 2026-06-15 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _blank_emails_to_null(apps, schema_editor):
    """Watumiaji wa zamani wana email='' (tupu) - badilisha kuwa NULL kabla
    ya kuweka 'unique=True', ili maandiko mengi ya tupu yasigongane."""
    User = apps.get_model('users', 'User')
    User.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookshareclick'),
        ('users', '0004_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Namba ya Simu'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by_book',
            field=models.ForeignKey(blank=True, help_text='Kitabu kilichoshirikiwa (share) ambacho kilimleta mtumiaji huyu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_signups', to='books.book', verbose_name='Alijiunga kupitia Kitabu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Barua Pepe'),
        ),
        migrations.RunPython(_blank_emails_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Barua Pepe'),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Usajili')], default='register', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
