# Generated by Django 6.0.5 on 2026-06-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='encrypted_audio',
            field=models.FileField(blank=True, null=True, upload_to='encrypted_audio/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='raw_file',
            field=models.FileField(blank=True, upload_to='raw_books/'),
        ),
    ]
