# Generated by Django 6.0.5 on 2026-06-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_audio_file_book_encrypted_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_authors',
            field=models.CharField(blank=True, default='', help_text='Majina ya waandishi, tenganisha kwa koma', max_length=500, verbose_name='Waandishi'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_language',
            field=models.CharField(blank=True, default='Kiswahili', max_length=50, verbose_name='Lugha ya Kitabu'),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, default='', help_text='Mfano: Toleo la 1, 2nd Edition', max_length=50, verbose_name='Toleo'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default='', help_text='ISBN-10 au ISBN-13', max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idadi ya Kurasa'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mchapishaji'),
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mwaka wa Kuchapishwa'),
        ),
    ]
