# Generated by Django 6.0.5 on 2026-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='min_plan_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Wote (pamoja na mpango wa Bure)'), (1, 'Basic na zaidi'), (2, 'Pro na zaidi'), (3, 'Premium pekee')], default=0, help_text='Kiwango cha chini cha usajili kinachohitajika kusoma kitabu hiki', verbose_name='Kiwango cha chini cha mpango'),
        ),
    ]
