# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_min_plan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='min_age',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Hakuna kikomo (Wote)'), (12, 'Miaka 12+'), (16, 'Miaka 16+'), (18, 'Miaka 18+ (Watu Wazima)')], default=0, help_text='Umri wa chini unaohitajika kusoma/kusikiliza kitabu hiki. 0 = hakuna kikomo.', verbose_name='Kikomo cha Umri'),
        ),
    ]
