# Generated by Django 6.0.5 on 2026-06-15 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_min_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShareClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('telegram', 'Telegram'), ('copy', 'Nakili Link'), ('app', 'Fungua App'), ('other', 'Nyingine')], default='', max_length=20, verbose_name='Mtandao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='books.book')),
                ('ref_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_share_clicks', to=settings.AUTH_USER_MODEL, verbose_name='Aliyeshare')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
