# Generated by Django 6.0.5 on 2026-06-10 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_add_library_metadata'),
        ('comments', '0002_add_replies_reactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flagged_words',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Maneno Yaliyogunduliwa'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Imeashiriwa (Lugha Chafu)'),
        ),
        migrations.AddField(
            model_name='comment',
            name='removed_by_author',
            field=models.BooleanField(default=False, verbose_name='Imeondolewa na Mwandishi'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('comment', 'Maoni Mapya'), ('reply', 'Jibu Jipya'), ('reaction', 'Mwitikio Mpya'), ('flagged', 'Ujumbe Umeashiriwa'), ('removed', 'Ujumbe Umeondolewa'), ('report', 'Ripoti Mpya'), ('moderation', 'Taarifa ya Usimamizi')], default='comment', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.book')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comments.comment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('profanity', 'Lugha Chafu / Matusi'), ('spam', 'Spam'), ('harassment', 'Unyanyasaji'), ('other', 'Nyingine')], default='other', max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Inasubiri Ukaguzi'), ('reviewed', 'Imepitiwa'), ('dismissed', 'Imeondolewa - Hakuna Hatua'), ('actioned', 'Hatua Imechukuliwa')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('comment', 'reporter')},
            },
        ),
    ]
