# Generated by Django 6.0.5 on 2026-06-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_moderation_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('comment', 'Maoni Mapya'), ('reply', 'Jibu Jipya'), ('reaction', 'Mwitikio Mpya'), ('flagged', 'Ujumbe Umeashiriwa'), ('removed', 'Ujumbe Umeondolewa'), ('report', 'Ripoti Mpya'), ('moderation', 'Taarifa ya Usimamizi'), ('author_message', 'Ujumbe kutoka kwa Mwandishi')], default='comment', max_length=20),
        ),
    ]
