# Generated by Django 6.0.5 on 2026-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['level']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Orodha ya faida za mpango huu (zinazoonekana kwa mtumiaji)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Bure (Free)'), (1, 'Basic'), (2, 'Pro'), (3, 'Premium')], default=0, help_text='Kiwango cha mpango: kadiri kinavyopanda ndivyo unavyopata vitabu zaidi'),
        ),
    ]
