# Generated by Django 6.0.5 on 2026-06-16 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookshareclick'),
        ('subscriptions', '0004_bilingual_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_book_limit', models.PositiveIntegerField(default=5, help_text='Idadi ya vitabu vya kulipa ambavyo msomaji wa Basic anaweza kusoma kwa kipindi', verbose_name='Idadi ya vitabu vya Basic')),
                ('pro_audio_limit', models.PositiveIntegerField(default=5, help_text='Idadi ya juu ya vitabu vya sauti ambavyo msomaji wa Pro anaweza kufungua', verbose_name='Idadi ya vitabu vya sauti vya Pro')),
            ],
            options={
                'verbose_name': 'Mipangilio ya Mfumo',
                'verbose_name_plural': 'Mipangilio ya Mfumo',
            },
        ),
        migrations.CreateModel(
            name='FreeBookSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_selections', to='books.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_book_selection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionBookAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_accessed', models.DateTimeField(auto_now_add=True)),
                ('is_audio', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_accesses', to='books.book')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_accesses', to='subscriptions.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book', 'subscription')},
            },
        ),
    ]
